import 'package:flutter/material.dart';

class TermsAndConditionPage extends StatelessWidget {
  const TermsAndConditionPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          "Terms And Conditions",
          style: TextStyle(
            fontSize: 22,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
        ),
        backgroundColor: Colors.blueAccent,
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildTitle("Terms and Conditions of Brilldaddy ECommerce Pvt Ltd"),
            const SizedBox(height: 10),
            _buildSection("1. TERMS",
                "Welcome to www.brilldaddy.com. This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This Agreement for the Terms and Conditions (hereinafter referred to as ‘Agreement’) of the Company’s website/mobile application (collectively referred to as “Systems”) describes certain terms and conditions to access and use the Systems of the Company."),
            _buildSection("2. ACCEPTANCE OF TERMS OF USE",
                "PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY. BY ACCESSING OUR SYSTEMS, YOU AGREE TO BE BOUND BY THE TERMS AND CONDITIONS BELOW. WE RESERVE THE RIGHT TO ALTER, AMEND AND MODIFY THESE TERMS AND CONDITIONS AT OUR SOLE DISCRETION. ALL AMENDMENTS AND MODIFICATIONS WILL BE DULY NOTIFIED ON OUR SYSTEMS. IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS, WE REQUEST YOU NOT TO ACCESS THIS WEBSITE."),
            _buildExpandableSection("3. USER ACCOUNT & SECURITY", [
              "• Any customer willing to use Our Systems may create an account by providing true, accurate and complete information as to name, address, email, and phone number.",
              "• You will, at all times, be responsible for maintaining the confidentiality of Your user name and password and be responsible for all activities that occur in Your account.",
              "• You agree that if You provide any information that is untrue, inaccurate or incomplete, You shall be solely responsible for the consequences thereof."
            ]),
            _buildExpandableSection("4. USER CONDUCT", [
              "• Use the Systems solely for lawful purposes and in full compliance with the Agreement, as well as applicable laws.",
              "• Not attempt to access the Systems using any methods other than those provided by Us.",
              "• Not engage in any activity that disrupts or interferes with the proper functioning of the Systems.",
              "• Not impersonate any individual or entity, including Our employees or representatives.",
              "• Not engage in fraudulent activities, including but not limited to fake payment verification, misuse of discounts, and unauthorized returns."
            ]),
            _buildExpandableSection("5. PRODUCTS & SERVICES", [
              "• The Company offers products and services as listed on Our Systems.",
              "• We reserve the right to modify, discontinue, or limit the availability of any product or service without prior notice."
            ]),
            _buildExpandableSection("6. SHIPPING & DELIVERY", [
              "• Estimated delivery times are provided for reference and are not guaranteed.",
              "• Delays due to unforeseen circumstances, third-party logistics, or force majeure are not Our responsibility."
            ]),
            _buildExpandableSection("7. RETURNS, REFUNDS & CANCELLATIONS", [
              "• Returns, refunds, and cancellations are subject to Our Return & Refund Policy, available at www.brilldaddy.com/refund-policy."
            ]),
            _buildExpandableSection("8. INTELLECTUAL PROPERTY RIGHTS", [
              "• The domain name www.brilldaddy.com is controlled, owned and operated by Brilldaddy E-commerce Pvt. Ltd.",
              "• All material on this site, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks, and other intellectual property rights.",
              "• Material on Our Systems is solely for Your personal, non-commercial use."
            ]),
            _buildExpandableSection("9. COMMUNICATION", [
              "• We may send You communication, notices or alerts from time to time.",
              "• You have agreed to receive any type of communication including but not limited to emails, SMS, phone calls or any other mode of communication from Us."
            ]),
            _buildExpandableSection("10. PAYMENTS", [
              "• The prices stated for the Products are inclusive of GST and shipping charges.",
              "• The customer can make the payment either by online payment or direct payment to Us via bank transfer/NEFT."
            ]),
            _buildExpandableSection("11. DISCLAIMER", [
              "• THE CONTENT AND ALL SERVICES ASSOCIATED WITH OUR SYSTEMS ARE PROVIDED TO YOU ON AN “AS-IS” AND “AS AVAILABLE” BASIS.",
              "• WE MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE CONTENT OR OPERATION OF OUR SYSTEMS."
            ]),
            _buildExpandableSection(
                "12. INDEMNITY AND LIMITATION OF LIABILITY", [
              "• You shall defend, indemnify and hold harmless the Company and its officers, directors, shareholders, and employees, from and against all loss, damages, claims and expenses.",
              "• WE SHALL IN NO EVENT BE RESPONSIBLE OR LIABLE TO YOU OR TO ANY THIRD PARTY FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES."
            ]),
            _buildExpandableSection("13. TERMINATION", [
              "• This Agreement may be terminated by You or Us under specific conditions.",
              "• We may terminate the Agreement if We learn that You have breached any of these terms and conditions."
            ]),
            _buildExpandableSection("14. JURISDICTION AND GOVERNING LAW", [
              "• This Agreement shall be governed by the laws of India.",
              "• The courts in Bangalore shall have the sole jurisdiction regarding the subject matter of this Agreement."
            ]),
            _buildExpandableSection("15. COUPONS, OFFERS AND EVENTS", [
              "• Users may redeem Brilldaddy-issued vouchers for purchases of Brilldaddy brand Products on our Systems.",
              "• Discounts and promotions apply only as specified at the time of purchase.",
              "• Brilldaddy events are protected by relevant intellectual property laws."
            ]),
            _buildSection(
                "16. CONTACT US",
                "For any queries regarding these Terms and Conditions, You may contact Us at:\n"
                    "• Company Name: BRILLDADDY ECOMMERCE PVT. LTD\n"
                    "• Customer Care Number: +91 9995124365\n"
                    "• Email: contact@brilldaddy.com\n"
                    "• Website: www.brilldaddy.com"),
          ],
        ),
      ),
    );
  }

  Widget _buildTitle(String text) {
    return Text(
      text,
      style: TextStyle(
        fontSize: 22,
        fontWeight: FontWeight.bold,
        color: Colors.blue.shade900,
      ),
    );
  }

  Widget _buildSection(String title, String content) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const SizedBox(height: 15),
        Text(
          title,
          style: TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.bold,
            color: Colors.blueAccent,
          ),
        ),
        const SizedBox(height: 8),
        Text(
          content,
          style: const TextStyle(fontSize: 16, height: 1.5),
        ),
      ],
    );
  }

  Widget _buildExpandableSection(String title, List<String> contentList) {
    return ExpansionTile(
      title: Text(
        title,
        style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
      ),
      children: contentList
          .map((item) => Padding(
                padding: const EdgeInsets.only(left: 16, bottom: 6),
                child: Text("• $item", style: const TextStyle(fontSize: 14)),
              ))
          .toList(),
    );
  }

  Widget _buildContactSection(String contactInfo) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 16),
      child: Row(
        children: [
          const Icon(Icons.email, color: Colors.blueAccent),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              contactInfo,
              style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w500),
            ),
          ),
        ],
      ),
    );
  }
}
